### ISSUE TITLE
translation bug

### ISSUE THREAD

**Issue by pv501977** [widgetfactory/jce-editor-jbtype#1]
Hi,

in the file en-GB.plg_jce_editor-jbtype.ini are bugs. There are chars ':' and should be '='
e.g. there is JBTYPE_DESC:"JB Type" and should be JBTYPE_DESC="JB Type"

**Comment by ryandemmer** [comment]
Fixed - https://github.com/widgetfactory/jce-editor-jbtype/commit/0640bfb924fd6c8920702008027ebb3e041671f1

Thank you
